### ISSUE TITLE
Interstellar todos

### ISSUE THREAD

**Issue by jwr1** [jwr1/interstellar#1]
## Fixes

- [x] Fix vote status not updating on detailed entry views: e55763688df9f62b12997515830344b701e1f47c
- [x] Fix the username that shows on the user screen: 0de2488149edf574ddbd45bab655d6d49fdaf76a
- [x] Fix inkwell corners for comments in search and user profile: 0de2488149edf574ddbd45bab655d6d49fdaf76a
- [x] Add app bar title to microblog post pages: 85b254d831cec8138c5320e11b174118df538105
- [x] Fix non preview post images from taking more space than needed: 85b254d831cec8138c5320e11b174118df538105

## Improvements

- [x] Clean up models (and move to separate directory) by using the freezed package, or something similar: ca0da7ff4bdf3e54f690a2cfa67bc636988a31c3
- [x] Check for duplicate items when loading pagination: c856953f31579c761f7553c24260bc47f6cfd4e0
- [x] Sort the list of accounts by host, then username: e61ddca2e507a8565fa188854fb461cdc46b1768

## Features

- [x] Icon design for Interstellar: #3
- [x] Implement comment editing: #4
- [ ] Improve markdown editing (like a preview tab)
- [x] Markdown user/magazine mentions: 0621e054409bb74a571ed5f62d0d6630645b2199 & 3634bbbf7701a4fe317ae23257bbec1b39d8ecca
- [ ] Markdown spoiler support
- [x] Implement [InteractiveViewer](https://api.flutter.dev/flutter/widgets/InteractiveViewer-class.html) for images when clicked on: 2dfec9ee629b3a6b115438da2ec926b9067955af
- [x] Directly embed video for YouTube links: b9f83ad1d6fe44d616034108732a09771ba8d1fe
- [ ] Support peertube embedding
- [x] Implement creating new threads: #7
- [x] Implement editing threads: #4
- [x] Add support for reporting content: e61ddca2e507a8565fa188854fb461cdc46b1768
- [x] Add support for blocking content: 60a69137f5860854597aa8acc01926b72d850a67
- [ ] Add i18n support
- [x] Add notification support: 92e83a4eaae7bd5a0dd8cbd51a4b76b81f2ac986
- [ ] Local push notification support
- [x] Use link dialog for thread links (similar to markdown links): 51dac891a78222089b8761d2a3b89b649e91799a
- [x] Add webview option for link dialogs: 51dac891a78222089b8761d2a3b89b649e91799a
- [x] Show option in triple dot menu to open a thread/post/comment in the browser: 7df6e88bc3858a59b6ff859387da809eb83e3c59
- [x] Show option to copy a URL: 959f59afe7cc3ab16fbdcaed27caa2339f7bfaf4
- [x] Handle comments past comment depth limit: ebc5dcedbe1773aacd54e62dcaf6a193c7d6d19a
- [ ] Handle clicking on notifications
- [x] Add messages interface in profile screen: 7b723e2d248d9ef08884120f569aef5e1cb93ce6
- [x] Add support for entry image uploading: #9
- [x] Add support for post image uploading: #12
- [x] Add a "compact" mode for wide/large screens where the UI is more similar to Kbin's web UI: c22dc3107ae99f6971085d904613c794a7a68f0f
- [x] Support for editing profile details: #19
- [x] Support for deleting avatar and cover from profile: #33
- [ ] Add filter/grouping/federation options to explore for magazines & users
- [x] Support for viewing and editing user account settings: #33
- [x] Add sorting options back to new user page: 4ca930aa1031b45682f879e1fd9c009bcc66b946

### Moderation

- [ ] View magazine rules
- [ ] View magazine owner and moderators
- [ ] Edit magazine details
- [ ] Mod actions (pin, remove, etc.) on content
- [ ] Create magazine
- [ ] View and manage reports

### Microblogging

- [x] Add support for viewing posts in feed: #2
- [x] Add support for voting/boosting posts: #2
- [x] Add support for replying to posts: #2
- [x] Add support for viewing posts in mag/user/domain feed: #4
- [x] Add support for creating new posts: #7
- [x] Add support for editing posts: #4

### Lemmy support

[Lemmy API docs here](https://lemmy.readme.io)

- [x] Comment viewing support: 069eb3700b93a9314d8976763b1c6b669b163d5a
- [x] Load magazine (community) details when the magazine specific page is opened: 29a337d4191f365ada54da4d418c4d4a84b90e2f
- [x] Load user details on user page (same as above): #24
- [x] Comment creation support: 21cf65a532ecade8c4fad34d15bcc01c8571179b
- [x] Add host back to lemmy user/magazine names when parsing model: e6a5a5d6e2e4d0fec38dc95a637eccffe0a0ac21
- [x] Search functionality: #25
- [x] Magazine sorting and filtering: 97cf4bfbfe6a52f543693be64254751c5814a3c3
- [ ] Lemmy specific sorting options
- [x] Post creation support: #28
- [ ] Notification viewing support
- [ ] Direct message support
- [ ] Fix post editing and deleting

**Comment by jwr1** [comment]
Closed in favor of separate issues, especially now that most of these are complete and Interstellar is generally functional.
