### ISSUE TITLE
General Lemmy support

### ISSUE THREAD

**Issue by jwr1** [jwr1/interstellar#35]
[Lemmy API docs here](https://lemmy.readme.io)

- [x] Comment viewing support: 069eb3700b93a9314d8976763b1c6b669b163d5a
- [x] Load magazine (community) details when the magazine specific page is opened: 29a337d4191f365ada54da4d418c4d4a84b90e2f
- [x] Load user details on user page (same as above): #24
- [x] Comment creation support: 21cf65a532ecade8c4fad34d15bcc01c8571179b
- [x] Add host back to lemmy user/magazine names when parsing model: e6a5a5d6e2e4d0fec38dc95a637eccffe0a0ac21
- [x] Search functionality: #25
- [x] Magazine sorting and filtering: 97cf4bfbfe6a52f543693be64254751c5814a3c3
- [x] Lemmy specific sorting options: #45
- [x] Post creation support: #28
- [ ] Notification viewing support
- [ ] Direct message support
- [x] Fix post editing and deleting: #48.

**Comment by jwr1** [comment]
Closed in favor of separate issues.
